package db

import (
	"gorm.io/gorm"
)

func SeedProyectos(db *gorm.DB) error {
	proyectos := []Proyecto{
		{Nombre: "BU REFORZAMIENTO PLACAS MOLINO HARINERO FASE 2", Zona: "BUCARAMANGA"},
		{Nombre: "BQ BARRANQUILLA", Zona: "BARRANQUILLA"},
		{Nombre: "CU ENVIGADO", Zona: "CUCUTA"},
		{Nombre: "BU MEDELLIN", Zona: "BUCARAMANGA"},
		{Nombre: "CU PAILITAS", Zona: "CUCUTA"},
		{Nombre: "CB MEDELLIN", Zona: "CENTROABASTOS"},
		{Nombre: "BU ANORI ANTIOQUIA", Zona: "BUCARAMANGA"},
		{Nombre: "CU CUCUTA", Zona: "CUCUTA"},
		{Nombre: "CB YONDO", Zona: "CENTROABASTOS"},
		{Nombre: "BU APARTADÓ", Zona: "BUCARAMANGA"},
		{Nombre: "MB ISLA SAINT JOHN", Zona: "MALAMBO"},
		{Nombre: "CU ARBOLEDAS", Zona: "CUCUTA"},
		{Nombre: "CB BOGOTA", Zona: "CENTROABASTOS"},
		{Nombre: "BU BELLO ANTIOQUIA", Zona: "BUCARAMANGA"},
		{Nombre: "MB ADECUACIÓNES BODEGAS", Zona: "MALAMBO"},
		{Nombre: "CU BOCHALEMA", Zona: "CUCUTA"},
		{Nombre: "CB CANTAGALLO", Zona: "CENTROABASTOS"},
		{Nombre: "BU CAUCASIA", Zona: "BUCARAMANGA"},
		{Nombre: "MB REPARACIÓN SILOS SCAFCO", Zona: "MALAMBO"},
		{Nombre: "CU CHINACOTA", Zona: "CUCUTA"},
		{Nombre: "CB SAN PABLO SUR DE BOLIVAR", Zona: "CENTROABASTOS"},
		{Nombre: "BU ENVIGADO", Zona: "BUCARAMANGA"},
		{Nombre: "MB MEDELLIN", Zona: "MALAMBO"},
		{Nombre: "CU EL TARRA N.S.", Zona: "CUCUTA"},
		{Nombre: "CB SANTA ROSA DEL SUR (BOLIVAR)", Zona: "CENTROABASTOS"},
		{Nombre: "BU GIRARDOTA(Antioquia)", Zona: "BUCARAMANGA"},
		{Nombre: "MB ARBOLETES ANTIOQUIA", Zona: "MALAMBO"},
		{Nombre: "CU EL ZULIA", Zona: "CUCUTA"},
		{Nombre: "CB SAN PABLO SUR DE BOLIVAR", Zona: "CENTROABASTOS"},
		{Nombre: "BU ITAGUI", Zona: "BUCARAMANGA"},
		{Nombre: "MB BELLO", Zona: "MALAMBO"},
		{Nombre: "CU GRAMALOTE", Zona: "CUCUTA"},
		{Nombre: "CHISCAS", Zona: "CENTROABASTOS"},
		{Nombre: "BU MUTATA ANTIOQUIA", Zona: "BUCARAMANGA"},
		{Nombre: "MB CAMPAMENTO ANTIOQUIA", Zona: "MALAMBO"},
		{Nombre: "CU LA ESPERANZA N.S.", Zona: "CUCUTA"},
		{Nombre: "CB ESPINO", Zona: "CENTROABASTOS"},
		{Nombre: "BU PUERTO BERRIO", Zona: "BUCARAMANGA"},
		{Nombre: "MB CAUCASIA", Zona: "MALAMBO"},
		{Nombre: "CU LOS PATIOS", Zona: "CUCUTA"},
		{Nombre: "CB AGUACHICA", Zona: "CENTROABASTOS"},
		{Nombre: "BU REMEDIOS", Zona: "BUCARAMANGA"},
		{Nombre: "MB ENVIGADO", Zona: "MALAMBO"},
		{Nombre: "CU OCAÑA", Zona: "CUCUTA"},
		{Nombre: "CB SAN ALBERTO", Zona: "CENTROABASTOS"},
		{Nombre: "BU VEGACHÍ", Zona: "BUCARAMANGA"},
		{Nombre: "MB ITAGUI", Zona: "MALAMBO"},
		{Nombre: "CU PAMPLONA", Zona: "CUCUTA"},
		{Nombre: "CB MOSQUERA", Zona: "CENTROABASTOS"},
		{Nombre: "BU YARUMAL", Zona: "BUCARAMANGA"},
		{Nombre: "MB SABANALARGA", Zona: "MALAMBO"},
		{Nombre: "CU PUERTO SANTANDER", Zona: "CUCUTA"},
		{Nombre: "CB NEMOCÓN CUNDINAMARCA", Zona: "CENTROABASTOS"},
		{Nombre: "BU YONDO ANTIOQUIA", Zona: "BUCARAMANGA"},
		{Nombre: "MB TURBO", Zona: "MALAMBO"},
		{Nombre: "CU SALAZAR", Zona: "CUCUTA"},
		{Nombre: "CB NEIVA", Zona: "CENTROABASTOS"},
		{Nombre: "BU CUBIERTA CUARTOS DE BULTOS ROBINSON", Zona: "BUCARAMANGA"},
		{Nombre: "MB YARUMAL", Zona: "MALAMBO"},
		{Nombre: "CU SAN CAYETANO", Zona: "CUCUTA"},
		{Nombre: "CB EL TARRA N.S.", Zona: "CENTROABASTOS"},
		{Nombre: "BU REPARACIÓN DE PATIO", Zona: "BUCARAMANGA"},
		{Nombre: "MB ADECUACIONES AREAS DE SERVICIO", Zona: "MALAMBO"},
		{Nombre: "CU SARDINATA", Zona: "CUCUTA"},
		{Nombre: "CB LA ESPERANZA N.S.", Zona: "CENTROABASTOS"},
		{Nombre: "BU BARRANQUILLA", Zona: "BUCARAMANGA"},
		{Nombre: "MB ILUMINACION BODEGAS", Zona: "MALAMBO"},
		{Nombre: "CU TIBU", Zona: "CUCUTA"},
		{Nombre: "CB BUCARAMANGA", Zona: "CENTROABASTOS"},
		{Nombre: "BU MALAMBO", Zona: "BUCARAMANGA"},
		{Nombre: "MB BARRANQUILLA", Zona: "MALAMBO"},
		{Nombre: "CU TOLEDO", Zona: "CUCUTA"},
		{Nombre: "CB ARATOCA", Zona: "CENTROABASTOS"},
		{Nombre: "BU SOLEDAD", Zona: "BUCARAMANGA"},
		{Nombre: "MB BARANOA", Zona: "MALAMBO"},
		{Nombre: "CU VILLA DEL ROSARIO", Zona: "CUCUTA"},
		{Nombre: "CB BARBOSA SANTANDER", Zona: "CENTROABASTOS"},
		{Nombre: "BU BOGOTA", Zona: "BUCARAMANGA"},
		{Nombre: "MB GALAPA", Zona: "MALAMBO"},
		{Nombre: "CU ARAUCA", Zona: "CUCUTA"},
		{Nombre: "CB BARICHARA", Zona: "CENTROABASTOS"},
		{Nombre: "BU CARTAGENA", Zona: "BUCARAMANGA"},
		{Nombre: "MB LURUACO", Zona: "MALAMBO"},
		{Nombre: "CU ARAUQUITA", Zona: "CUCUTA"},
		{Nombre: "CB BARRANCABERMEJA", Zona: "CENTROABASTOS"},
		{Nombre: "BU CANTAGALLO", Zona: "BUCARAMANGA"},
		{Nombre: "MB MALAMBO", Zona: "MALAMBO"},
		{Nombre: "CU FORTUL ARAUCA", Zona: "CUCUTA"},
		{Nombre: "CB CAPITANEJO", Zona: "CENTROABASTOS"},
		{Nombre: "BU SAN PABLO SUR DE BOLIVA", Zona: "BUCARAMANGA"},
		{Nombre: "MB PALMAR DE VARELA", Zona: "MALAMBO"},
		{Nombre: "CU SARAVENA", Zona: "CUCUTA"},
		{Nombre: "CB CARCASI", Zona: "CENTROABASTOS"},
		{Nombre: "BU SANTA ROSA DEL SUR (BOLIVAR)", Zona: "BUCARAMANGA"},
		{Nombre: "MB POLONUEVO", Zona: "MALAMBO"},
		{Nombre: "CU TAME", Zona: "CUCUTA"},
		{Nombre: "CB CERRITO", Zona: "CENTROABASTOS"},
		{Nombre: "BU TUNJA", Zona: "BUCARAMANGA"},
		{Nombre: "MB PUERTO COLOMBIA", Zona: "MALAMBO"},
		{Nombre: "CB CHARALA", Zona: "CENTROABASTOS"},
		{Nombre: "BU BELEN", Zona: "BUCARAMANGA"},
		{Nombre: "MB SABANAGRANDE", Zona: "MALAMBO"},
		{Nombre: "CB CIMITARRA", Zona: "CENTROABASTOS"},
		{Nombre: "BU BOAVITA", Zona: "BUCARAMANGA"},
		{Nombre: "MB SABANALARGA ATLANTICO", Zona: "MALAMBO"},
		{Nombre: "CB CONCEPCION SANTANDER", Zona: "CENTROABASTOS"},
		{Nombre: "BU CERINZA", Zona: "BUCARAMANGA"},
		{Nombre: "MB SANTA LUCIA", Zona: "MALAMBO"},
		{Nombre: "CB CURITI", Zona: "CENTROABASTOS"},
		{Nombre: "BU CHISCAS", Zona: "BUCARAMANGA"},
		{Nombre: "MB SANTO TOMAS", Zona: "MALAMBO"},
		{Nombre: "CB EL CARMEN DE CHUCURI", Zona: "CENTROABASTOS"},
		{Nombre: "BU DUITAMA", Zona: "BUCARAMANGA"},
		{Nombre: "MB SOLEDAD", Zona: "MALAMBO"},
		{Nombre: "CB EL PLAYON", Zona: "CENTROABASTOS"},
		{Nombre: "BU COCUY", Zona: "BUCARAMANGA"},
		{Nombre: "MB SUAN", Zona: "MALAMBO"},
		{Nombre: "CB ENCINO", Zona: "CENTROABASTOS"},
		{Nombre: "BU ESPINO", Zona: "BUCARAMANGA"},
		{Nombre: "MB PISO EPOXICO MOLINO", Zona: "MALAMBO"},
		{Nombre: "CB FLORIDABLANCA", Zona: "CENTROABASTOS"},
		{Nombre: "BU GUACAMAYAS", Zona: "BUCARAMANGA"},
		{Nombre: "MB OFICINAS Y LABORATORIO TEMPORALES PLANTA", Zona: "MALAMBO"},
		{Nombre: "CB GIRON", Zona: "CENTROABASTOS"},
		{Nombre: "BU GUICAN", Zona: "BUCARAMANGA"},
		{Nombre: "MB OFICINAS TEMPORAL LOGISTICA-INVENTARIOS-SST-CONTRATISTAS", Zona: "MALAMBO"},
		{Nombre: "CB GUACA", Zona: "CENTROABASTOS"},
		{Nombre: "BU LA UVITA", Zona: "BUCARAMANGA"},
		{Nombre: "MB ADECUACION EDIFICIO LOTE 8", Zona: "MALAMBO"},
		{Nombre: "CB LANDAZURI", Zona: "CENTROABASTOS"},
		{Nombre: "BU VILLA DE LEYVA", Zona: "BUCARAMANGA"},
		{Nombre: "REEMPLAZO MADERA MEZANINE", Zona: "MALAMBO"},
		{Nombre: "CB LEBRIJA", Zona: "CENTROABASTOS"},
		{Nombre: "BU MONIQUIRA", Zona: "BUCARAMANGA"},
		{Nombre: "MB VENTILACIÓN DE MOLINO", Zona: "MALAMBO"},
		{Nombre: "CB LOS SANTOS", Zona: "CENTROABASTOS"},
		{Nombre: "BU PAIPA", Zona: "BUCARAMANGA"},
		{Nombre: "MB BOGOTA", Zona: "MALAMBO"},
		{Nombre: "CB MACARAVITA", Zona: "CENTROABASTOS"},
		{Nombre: "BU PANQUEBA", Zona: "BUCARAMANGA"},
		{Nombre: "MB CANALES DE CUBIERTAS", Zona: "MALAMBO"},
		{Nombre: "CB MALAGA", Zona: "CENTROABASTOS"},
		{Nombre: "BU SAN MATEO", Zona: "BUCARAMANGA"},
		{Nombre: "MB CARTAGENA", Zona: "MALAMBO"},
		{Nombre: "CB MOLAGAVITA", Zona: "CENTROABASTOS"},
		{Nombre: "BU SANTANA", Zona: "BUCARAMANGA"},
		{Nombre: "MB CALAMAR", Zona: "MALAMBO"},
		{Nombre: "CB OIBA", Zona: "CENTROABASTOS"},
		{Nombre: "BU SANTA ROSA VITERBO", Zona: "BUCARAMANGA"},
		{Nombre: "MB CORDOBA (Bolivar)", Zona: "MALAMBO"},
		{Nombre: "CB RIONEGRO SANTANDER", Zona: "CENTROABASTOS"},
		{Nombre: "BU SOATA", Zona: "BUCARAMANGA"},
		{Nombre: "MB EL CARMEN DE BOLIVAR", Zona: "MALAMBO"},
		{Nombre: "CB SABANA DE TORRES", Zona: "CENTROABASTOS"},
		{Nombre: "BU SOGAMOSO", Zona: "BUCARAMANGA"},
		{Nombre: "MB MAGANGUE", Zona: "MALAMBO"},
		{Nombre: "CB SAN ANDRES SANTANDER", Zona: "CENTROABASTOS"},
		{Nombre: "BU SORACA BOYACA", Zona: "BUCARAMANGA"},
		{Nombre: "MN MARIA LA BAJA", Zona: "MALAMBO"},
		{Nombre: "CB SAN GIL", Zona: "CENTROABASTOS"},
		{Nombre: "BU SUSACON", Zona: "BUCARAMANGA"},
		{Nombre: "MB MOMPOX", Zona: "MALAMBO"},
		{Nombre: "SAN JOAQUIN SANTANDER", Zona: "CENTROABASTOS"},
		{Nombre: "BU TIPACOQUE", Zona: "BUCARAMANGA"},
		{Nombre: "MB SAN JACINTO", Zona: "MALAMBO"},
		{Nombre: "CB SAN MIGUEL", Zona: "CENTROABASTOS"},
		{Nombre: "BU CALOTO CAUCA", Zona: "BUCARAMANGA"},
		{Nombre: "MB SAN JUAN NEPONUCENO", Zona: "MALAMBO"},
		{Nombre: "CB SAN VICENTE DE CHUCURI", Zona: "CENTROABASTOS"},
		{Nombre: "BU VALLEDUPAR", Zona: "BUCARAMANGA"},
		{Nombre: "MB TURBACO", Zona: "MALAMBO"},
		{Nombre: "CB SOCORRO", Zona: "CENTROABASTOS"},
		{Nombre: "BU AGUACHICA", Zona: "BUCARAMANGA"},
		{Nombre: "MB CONSTRUCCION PATIO DE CARGUE", Zona: "MALAMBO"},
		{Nombre: "CB SUCRE", Zona: "CENTROABASTOS"},
		{Nombre: "BU BOSCONIA", Zona: "BUCARAMANGA"},
		{Nombre: "MB ADECUACION ZONA POSTERIOR PLANTA", Zona: "MALAMBO"},
		{Nombre: "CB VILLANUEVA SANTANDER", Zona: "CENTROABASTOS"},
		{Nombre: "BU CURUMANI", Zona: "BUCARAMANGA"},
		{Nombre: "MB VALLEDUPAR", Zona: "MALAMBO"},
		{Nombre: "CB ZAPATOCA", Zona: "CENTROABASTOS"},
		{Nombre: "BU PAILITAS", Zona: "BUCARAMANGA"},
		{Nombre: "MB AGUACHICA (Cesar)", Zona: "MALAMBO"},
		{Nombre: "CB ARAUCA", Zona: "CENTROABASTOS"},
		{Nombre: "BU SAN ALBERTO", Zona: "BUCARAMANGA"},
		{Nombre: "MB AGUSTIN CODAZZI - CESAR", Zona: "MALAMBO"},
		{Nombre: "CB FORTUL ARAUCA", Zona: "CENTROABASTOS"},
		{Nombre: "BU SAN MARTIN", Zona: "BUCARAMANGA"},
		{Nombre: "MB BOSCONIA", Zona: "MALAMBO"},
		{Nombre: "CB SARAVENA", Zona: "CENTROABASTOS"},
		{Nombre: "BU MONTERIA", Zona: "BUCARAMANGA"},
		{Nombre: "MB CHIMICHAGUA", Zona: "MALAMBO"},
		{Nombre: "CB TAME", Zona: "CENTROABASTOS"},
		{Nombre: "BU CHIA", Zona: "BUCARAMANGA"},
		{Nombre: "MB CURUMANI", Zona: "MALAMBO"},
		{Nombre: "CB SAN JOSE DE GUAVIARE", Zona: "CENTROABASTOS"},
		{Nombre: "BU COTA CUNDINAMARCA", Zona: "BUCARAMANGA"},
		{Nombre: "MB EL COPEY", Zona: "MALAMBO"},
		{Nombre: "BU FACATATIVA", Zona: "BUCARAMANGA"},
		{Nombre: "MB JAGUA DE IBIRICO_CESAR", Zona: "MALAMBO"},
		{Nombre: "BU FUNZA CUNDINAMARCA", Zona: "BUCARAMANGA"},
		{Nombre: "MB MONTERIA", Zona: "MALAMBO"},
		{Nombre: "BU MOSQUERA", Zona: "BUCARAMANGA"},
		{Nombre: "MB CERETE", Zona: "MALAMBO"},
		{Nombre: "BU NEMOCÓN CUNDINAMARCA", Zona: "BUCARAMANGA"},
		{Nombre: "MB CHINÚ", Zona: "MALAMBO"},
		{Nombre: "BU TENJO", Zona: "BUCARAMANGA"},
		{Nombre: "MB CIÉNAGA DE ORO", Zona: "MALAMBO"},
		{Nombre: "BU EL CARMEN", Zona: "BUCARAMANGA"},
		{Nombre: "MB LORICA", Zona: "MALAMBO"},
		{Nombre: "BU NEIVA", Zona: "BUCARAMANGA"},
		{Nombre: "MB MONTELIBANO", Zona: "MALAMBO"},
		{Nombre: "BU RIOHACHA", Zona: "BUCARAMANGA"},
		{Nombre: "MB PLANETA RICA", Zona: "MALAMBO"},
		{Nombre: "BU BARRANCAS", Zona: "BUCARAMANGA"},
		{Nombre: "MB SAHAGUN", Zona: "MALAMBO"},
		{Nombre: "BU MAICAO", Zona: "BUCARAMANGA"},
		{Nombre: "MB SAN ANTERO", Zona: "MALAMBO"},
		{Nombre: "BU URIBIA", Zona: "BUCARAMANGA"},
		{Nombre: "MB FACATATIVA", Zona: "MALAMBO"},
		{Nombre: "BU SANTA MARTA", Zona: "BUCARAMANGA"},
		{Nombre: "MB RIVERA HUILA", Zona: "MALAMBO"},
		{Nombre: "BU VILLAVICENCIO", Zona: "BUCARAMANGA"},
		{Nombre: "MB RIOHACHA", Zona: "MALAMBO"},
		{Nombre: "BU CUCUTA", Zona: "BUCARAMANGA"},
		{Nombre: "MB ALBANIA", Zona: "MALAMBO"},
		{Nombre: "BU ABREGO", Zona: "BUCARAMANGA"},
		{Nombre: "MB BARRANCAS", Zona: "MALAMBO"},
		{Nombre: "BU CHINACOTA", Zona: "BUCARAMANGA"},
		{Nombre: "MB MAICAO", Zona: "MALAMBO"},
		{Nombre: "BU EL TARRA N.S.", Zona: "BUCARAMANGA"},
		{Nombre: "MB URIBIA", Zona: "MALAMBO"},
		{Nombre: "BU LA ESPERANZA N.S.", Zona: "BUCARAMANGA"},
		{Nombre: "MB SANTA MARTA", Zona: "MALAMBO"},
		{Nombre: "BU OCAÑA", Zona: "BUCARAMANGA"},
		{Nombre: "MB ARACATACA", Zona: "MALAMBO"},
		{Nombre: "BU PAMPLONA", Zona: "BUCARAMANGA"},
		{Nombre: "MB ARIGUANI", Zona: "MALAMBO"},
		{Nombre: "BU SARDINATA", Zona: "BUCARAMANGA"},
		{Nombre: "MB CIENAGA", Zona: "MALAMBO"},
		{Nombre: "BU TIBU", Zona: "BUCARAMANGA"},
		{Nombre: "MB EL BANCO", Zona: "MALAMBO"},
		{Nombre: "BU TOLEDO", Zona: "BUCARAMANGA"},
		{Nombre: "MB EL RETEN", Zona: "MALAMBO"},
		{Nombre: "BU VILLA DEL ROSARIO", Zona: "BUCARAMANGA"},
		{Nombre: "MB FUNDACION", Zona: "MALAMBO"},
		{Nombre: "BU PEREIRA", Zona: "BUCARAMANGA"},
		{Nombre: "MB PIVIJAY", Zona: "MALAMBO"},
		{Nombre: "BU BUCARAMANGA", Zona: "BUCARAMANGA"},
		{Nombre: "MB PLATO", Zona: "MALAMBO"},
		{Nombre: "BU ARATOCA", Zona: "BUCARAMANGA"},
		{Nombre: "MB SITIONUEVO MAGDALENA", Zona: "MALAMBO"},
		{Nombre: "BU BARBOSA SANTANDER", Zona: "BUCARAMANGA"},
		{Nombre: "MB CUCUTA", Zona: "MALAMBO"},
		{Nombre: "BU BARICHARA", Zona: "BUCARAMANGA"},
		{Nombre: "MB BUCARAMANGA", Zona: "MALAMBO"},
		{Nombre: "BU BARRANCABERMEJA", Zona: "BUCARAMANGA"},
		{Nombre: "MB FLORIDABLANCA (SDER)", Zona: "MALAMBO"},
		{Nombre: "BU CAPITANEJO", Zona: "BUCARAMANGA"},
		{Nombre: "MB SINCELEJO", Zona: "MALAMBO"},
		{Nombre: "BU CARCASÍ", Zona: "BUCARAMANGA"},
		{Nombre: "MB COROZAL", Zona: "MALAMBO"},
		{Nombre: "BU CERRITO", Zona: "BUCARAMANGA"},
		{Nombre: "MB COVEÑAS", Zona: "MALAMBO"},
		{Nombre: "BU CHARALA", Zona: "BUCARAMANGA"},
		{Nombre: "MB GALERAS SUCRE", Zona: "MALAMBO"},
		{Nombre: "BU CHARTA", Zona: "BUCARAMANGA"},
		{Nombre: "MB LOS PALMITOS", Zona: "MALAMBO"},
		{Nombre: "BU CIMITARRA", Zona: "BUCARAMANGA"},
		{Nombre: "MB OVEJAS", Zona: "MALAMBO"},
		{Nombre: "BU CONCEPCION SANTANDER", Zona: "BUCARAMANGA"},
		{Nombre: "MB SAN MARCOS", Zona: "MALAMBO"},
		{Nombre: "BU CONFINES", Zona: "BUCARAMANGA"},
		{Nombre: "MB SAN ONOFRE", Zona: "MALAMBO"},
		{Nombre: "BU COROMORO", Zona: "BUCARAMANGA"},
		{Nombre: "MB SANTIAGO DE TOLU", Zona: "MALAMBO"},
		{Nombre: "BU CURITI", Zona: "BUCARAMANGA"},
		{Nombre: "MB TOLU VIEJO", Zona: "MALAMBO"},
		{Nombre: "BU EL CARMEN DE CHUCURI", Zona: "BUCARAMANGA"},
		{Nombre: "MB CALI", Zona: "MALAMBO"},
		{Nombre: "BU EL PLAYON", Zona: "BUCARAMANGA"},
		{Nombre: "MB SAN ANDRES ISLAS", Zona: "MALAMBO"},
		{Nombre: "BU ENCINO", Zona: "BUCARAMANGA"},
		{Nombre: "MB PROVIDENCIA", Zona: "MALAMBO"},
		{Nombre: "BU ENCISO", Zona: "BUCARAMANGA"},
		{Nombre: "BU FLORIDABLANCA", Zona: "BUCARAMANGA"},
		{Nombre: "BU GAMBITA", Zona: "BUCARAMANGA"},
		{Nombre: "BU GIRON", Zona: "BUCARAMANGA"},
		{Nombre: "BU GUACA", Zona: "BUCARAMANGA"},
		{Nombre: "BU GUEPSA", Zona: "BUCARAMANGA"},
		{Nombre: "BU LEBRIJA", Zona: "BUCARAMANGA"},
		{Nombre: "BU LOS SANTOS", Zona: "BUCARAMANGA"},
		{Nombre: "BU MACARAVITA", Zona: "BUCARAMANGA"},
		{Nombre: "BU MALAGA", Zona: "BUCARAMANGA"},
		{Nombre: "BU MATANZA", Zona: "BUCARAMANGA"},
		{Nombre: "BU MOLAGAVITA", Zona: "BUCARAMANGA"},
		{Nombre: "BU OIBA", Zona: "BUCARAMANGA"},
		{Nombre: "BU PIEDECUESTA", Zona: "BUCARAMANGA"},
		{Nombre: "BU PUENTE NACIONAL", Zona: "BUCARAMANGA"},
		{Nombre: "BU PUERTO WILCHES", Zona: "BUCARAMANGA"},
		{Nombre: "BU RIONEGRO SANTANDER", Zona: "BUCARAMANGA"},
		{Nombre: "BU SABANA DE TORRES", Zona: "BUCARAMANGA"},
		{Nombre: "BU SAN ANDRES SANTANDER", Zona: "BUCARAMANGA"},
		{Nombre: "BU SAN GIL", Zona: "BUCARAMANGA"},
		{Nombre: "SAN JOAQUIN SANTANDER", Zona: "BUCARAMANGA"},
		{Nombre: "BU SAN JOSE DE MIRANDA", Zona: "BUCARAMANGA"},
		{Nombre: "BU SANMIGUEL", Zona: "BUCARAMANGA"},
		{Nombre: "BU SAN VICENTE DE CHUCURI", Zona: "BUCARAMANGA"},
		{Nombre: "BU SANTA HELENA DEL OPON", Zona: "BUCARAMANGA"},
		{Nombre: "BU SIMACOTA", Zona: "BUCARAMANGA"},
		{Nombre: "BU SOCORRO", Zona: "BUCARAMANGA"},
		{Nombre: "BU SUAITA", Zona: "BUCARAMANGA"},
		{Nombre: "BU SUCRE", Zona: "BUCARAMANGA"},
		{Nombre: "BU TONA", Zona: "BUCARAMANGA"},
		{Nombre: "BU VELEZ", Zona: "BUCARAMANGA"},
		{Nombre: "BU VILLANUEVA SANTANDER", Zona: "BUCARAMANGA"},
		{Nombre: "BU ZAPATOCA", Zona: "BUCARAMANGA"},
		{Nombre: "BU IBAGUE", Zona: "BUCARAMANGA"},
		{Nombre: "BU CALI", Zona: "BUCARAMANGA"},
		{Nombre: "BU ARAUCA", Zona: "BUCARAMANGA"},
		{Nombre: "BU ARAUQUITA", Zona: "BUCARAMANGA"},
		{Nombre: "BU FORTUL ARAUCA", Zona: "BUCARAMANGA"},
		{Nombre: "BU SARAVENA", Zona: "BUCARAMANGA"},
		{Nombre: "BU TAME", Zona: "BUCARAMANGA"},
		{Nombre: "BU YOPAL", Zona: "BUCARAMANGA"},
		{Nombre: "BU SAN JOSE DE GUAVIARE", Zona: "BUCARAMANGA"},
	}

	for _, p := range proyectos {
		if err := db.Where("nombre = ? AND zona = ?", p.Nombre, p.Zona).FirstOrCreate(&p).Error; err != nil {
			return err
		}
	}
	return nil
}
